### ISSUE TITLE
comments from Dan Handwerker

### ISSUE THREAD

**Issue by poldrack** [poldrack/myconnectome-vm#15]
I've run into an issue, but here are some general comments first. I'm just giving a few comments here, but, if it's more convenient for you, I could edit the README.md file and send those edits back to you either through github or by email.

The README.md file lists the python dependencies, but "nilearn" is missing.
I was able to get it with "pip install nilearn"

The readme instructions do have any explanation of which functions to run. With some searching, I found run_everything.py in the scripts subdirectory, but that could be more explicit and there could be brief explanations of the other functions in the scripts directory.

My first real issue occurred when I tried to run the scripts. I repeatedly had some sort of connection disruption and the get_base_data() function crashed. I'm pretty sure the disruption wasn't on my end, but I'm not sure. I was able to keep rerunning, "python ./utils/get_data.py --base" to get more and more files downloaded, but this is a function that could also be mentioned in the readme. 

Eventually, this stopped working when some checksums failed. I've included that error below.
$ python get_data.py --base
getting base starting data for main analysis...
downloading basefilelist.txt
md5sum does not match for  basefilelist.txt d19f6cac4be1b3ccced8f84007743112
downloading robots.txt
md5sum does not match for  robots.txt 19c0f94d592716d2a32ce9d15f6be142
downloading rna-seq/snyderome/snyderome_files.txt
md5sum does not match for  rna-seq/snyderome/snyderome_files.txt ed0601074d4537e65aecd7f2624fe5f4

That's where I've stopped for now since this looks like more than just a coding quirk.

**Comment by vsoch** [comment]
Is there a reason he was running "run_everything.py" manually? The error in checksums indicate a problem downloading, and we don't have much control over that other than to have checks for the integrity of the files, and skip over analyses when the downloads don't work (and alert the user to this, and to show the results that were able to run with data.) However, a problem downloading one file probably means a problem downloading many, and there might not be much left to look at. In the meantime we might consider adding a note to the README about the essential-ness of a consistent internet connection, and in the long run we need to think of a more solid way to deliver these files.

**Comment by poldrack** [comment]
he was not running it from within the VM, but rather from the standalone python package

**Comment by vsoch** [comment]
ah, ok. Seems that we lose less control when it's run on the user's OS.

**Comment by erikssona** [comment]
Just tried running the analysis in the VM and possibly having the same issues as mentioned above the error tracing back to get_data.py. Any progress on this?

**Comment by poldrack** [comment]
can you send the log file?

**Comment by erikssona** [comment]
Here it is. Seems it could have something to do with there being no data at the amazon address indicated?

[myconnectome_vm_err.txt](https://github.com/poldrack/myconnectome-vm/files/75288/myconnectome_vm_err.txt)

**Comment by poldrack** [comment]
hmm, where do you see that?  the main thing I see is that it’s having trouble installing some of the R packages for your version of R.

**Comment by erikssona** [comment]
At the very end. This is where it's looking at http://s3.amazonaws.com/openfmri/ds031/myconnectome-vm

File "build/bdist.linux-x86_64/egg/myconnectome/utils/get_data.py", line 82, in get_base_data
File "build/bdist.linux-x86_64/egg/myconnectome/utils/get_data.py", line 63, in get_list_data
IndexError: list index out of range

**Comment by vsoch** [comment]
Could you send the myconnectome_vm_out.txt file as well?

**Comment by erikssona** [comment]
that's easy, it's just:

environment variable DAVID_EMAIL recommended but not required
all environment variables present
Found R version 3.2.3
MATLAB was not detected - precomputed results will be downloaded
getting data for main analysis...
downloading

**Comment by poldrack** [comment]
I think it might have been an AWS permissions issue. I just reset that
entire folder to be public, can you try it again?

**Comment by erikssona** [comment]
I get exactly the same result.

**Comment by erikssona** [comment]
Tried running the script on my machine:

`getting data for main analysis...
Traceback (most recent call last):
  File "myconnectome/scripts/run_everything.py", line 90, in <module>
    execfile('%s/scripts/rsfmri_analysis.py'%basepath)
  File "/Users/erikssona/myconnectome/myconnectome/myconnectome/scripts/rsfmri_analysis.py", line 30, in <module>
    get_base_data()
  File "build/bdist.macosx-10.5-x86_64/egg/myconnectome/utils/get_data.py", line 82, in get_base_data
  File "build/bdist.macosx-10.5-x86_64/egg/myconnectome/utils/get_data.py", line 55, in get_list_data
IndexError: list index out of range`

Also, in the results folder, the output reads:
`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>ds031/myconnectome-vm/&lt;</Key><RequestId>CE0E05A41C23EBCB</RequestId><HostId>oJJvkUYShSQbf11gsprh3dughb1z0M9HdEqz+i15P31Yt/RNz7Oz0ajndkGbcWXX</HostId></Error>`

Which is quite similar to what appears in my browser when I go to http://s3.amazonaws.com/openfmri/http://s3.amazonaws.com/openfmri/ds031/myconnectome-vm

**Comment by erikssona** [comment]
It seems that get_data.py should point to http://myconnectome.s3.amazonaws.com/ instead.

Then on lines 21 and 61, edits need to be made to include the subdirectory "/base" in the full file names. After making these edits I was able to get all of the files to download, and run_everything.py is chugging away...

**Comment by vsoch** [comment]
Haha, I think we figured this out at the same time! Although I'm a bit behind, just testing [this now](https://github.com/poldrack/myconnectome/pull/13), and my links are the "non elegant" aws version (will update in a second).  It appears that we had some reorganization with updating the openfmri site, and moving the data to that different bucket. I'm glad we are figuring this out!

**Comment by vsoch** [comment]
If it hits [this](https://github.com/vsoch/myconnectome/blob/1d4187a54be0f7120d6441525e8c797a15379920/myconnectome/utils/get_data.py#L137) it will bug out, because I don't see that file. I need to go back to sleep for a bit, but Russ gets up super early and take over the last bits!

**Comment by vsoch** [comment]
Just a quick update - this fixed the bug for me. Russ can take a look and merge the PR, and if you do:

```
  vagrant suspend
  vagrant destroy (Y)
```

and then in the Vagrantfile change this line:

```
  git clone https://github.com/poldrack/myconnectome.git $HOME/myconnectome
```

to this:

```
  git clone https://github.com/vsoch/myconnectome.git $HOME/myconnectome
```

and then restart the virtual machine

```
  vagrant up
```

that should be a workaround until we have a chance to merge the PR. I haven't checked the rest of the run beyond seeing that the downloads worked and the results are coming in! Please post if you have additional issues, and Happy New Year! :D

**Comment by poldrack** [comment]
actually, the original url was correct:

https://s3.amazonaws.com/openfmri/ds031/myconnectome-vm https://s3.amazonaws.com/openfmri/ds031/myconnectome-vm

otherwise I will have to pay for downloads since that other myconnectome bucket is in my own S3 space rather than on openfmri :-)

What seemed to have happened (and I don’t quite know why) is that the MD5 files were removed from the myconnectome-vm directory.  I have uploaded them and now “python get_data.py —base” seems to work correctly for me.  please confirm that it works for you as well.
cheers
russ

**Comment by erikssona** [comment]
Oh no! We don't want that! The openfmri bucket works for me now.

Happy New Year!
